---
name: Empty Branch
description: Creates an empty branch
inputs:
  branch:
    description: Branch name
    required: true
    default: data
  if-exists:
    description: What action to take if the branch already exists; fail, skip, checkout, or wipe
    required: true
    default: checkout
outputs:
  created:
    description: If the branch was successfully created (or checked out)
runs:
  using: composite
  steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Existing branch behavior
      shell: bash
      run: |
        echo "Checking if branch exists: ${{ inputs.branch }}"
        if git branch | grep -q ${{ inputs.branch }}; then
          echo "Branch '${{ inputs.branch }}' already exists..."
          case ${{ inputs.if-exists }} in
            fail)
              echo "Instructed to fail."
              echo "created=false" >> $GITHUB_OUTPUT
              exit 1
              ;;
            skip)
              echo "Instructed to skip"
              echo "created=false" >> $GITHUB_OUTPUT
              ;;
            checkout)
              echo "Checking out instead..."
              git checkout ${{ inputs.branch }}
              echo "created=true" >> $GITHUB_OUTPUT
              ;;
            wipe)
              echo "Ordered to nuke branch!"
              echo " --- NOT YET IMPLEMENTED ---"
              echo "created=false" >> $GITHUB_OUTPUT
              exit 1
              ;;
          esac
          exit 0
        fi

    - name: Do the things
      shell: bash
      run: |
        echo "Branch doesn't exist..."
        echo "Creating empty branch: ${{ inputs.branch }}"
        git switch --orphan ${{ inputs.branch }}
        echo "created=true" >> $GITHUB_OUTPUT
        exit 0
...
