on: workflow_dispatch

jobs:
  make_empty:
    runs-on: ubuntu-latest
    name: Try to make an empty branch
    steps:
      #- name: checkout
      - uses: actions/checkout@v4

      - run: ls -R
      
      - id: foo
        uses: omnikron13/empty-branch-action@v0.1.1
        with:
          branch: test-empty-1
          
      - name: debug print
        run: ls -R
